server:
  port: 5003

spring:
  application:
    name: SUBMISSION-SERVICE

  datasource:
    url: jdbc:postgresql://localhost:5432/submission_service
    username: $$$$$$
    password: ------
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
