
server:
  port: 5002

spring:
  application:
    name: TASK-SERVICE

  datasource:
    url: jdbc:postgresql://localhost:5432/task_service
    username: $$$$$$
    password: $$$$$$
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#    show-sql: true
#    generate-ddl: true
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
